index_hkTimeUTC=1;
index_timeUtc=2;
index_selSBband=3;
index_sBandPStat=4;
index_sBandRStat=5;
index_fswOpMode=6;
index_fswSubOpMode=7;
index_fswRebootCnt=8;
index_fswMassMem=9;
index_obcTemp=10;
index_edacCnt=11;
index_spDepStatXp=12;
index_spDepStatXn=13;
index_spDepStatYn=14;
index_spDepGpioStatXp=15;
index_spDepGpioStatXn=16;
index_spCepGpioStatYn=17;
index_antDepStatXp=18;
index_antDepStatXn=19;
index_spStationTempXp=20;
index_spStationTempXn=21;
index_spStationTempYn=22;
index_spStationTempYp=23;
index_spUpTopTempXp=24;
index_spUpTopTempXn=25;
index_spUpTopTempYn=26;
index_spUpBotTempXp=27;
index_spUpBotTempXn=28;
index_spUpBotTempYn=29;
index_adcEocYpZn=30;
index_adcEocYpZp=31;
index_adcEocYnZn=32;
index_adcEocYnZp=33;
index_adcAntXp=34;
index_adcAntXn=35;
index_adcPdhsCaseTemp=36;
index_adcEwc27CaseTemp=37;
index_epsDockDevFramStat=38;
index_epsDockDevAdc1Stat=39;
index_epsDockDevAdc2Stat=40;
index_epsDockDevAdc3Stat=41;
index_epsDockDevTempSenStat=42;
index_epsDockDevRtcStat=43;
index_epsMpptMode=44;
index_epsAcuDevFramStat=45;
index_epsAcuDevAdc1Stat=46;
index_epsAcuDevAdc2Stat=47;
index_epsAcuDevDac1Stat=48;
index_epsAcuDevDac2Stat=49;
index_epsAcuDevDac3Stat=50;
index_epsAcuDevTempSenStat=51;
index_bat1HeatEnableStat=52;
index_bat2HeatEnableStat=53;
index_epsPduDevFramStat=54;
index_epsPduDevAdc1Stat=55;
index_epsPduDevAdc2Stat=56;
index_epsPduDevTempSenStat=57;
index_epsPwrSwBatStat=58;
index_epsPwrSwObcStat=59;
index_epsPwrSwAocsStat=60;
index_epsPwrSwGpsStat=61;
index_epsPwrSwSBandStat=62;
index_epsPwrSwAntStat=63;
index_epsPwrSwEwc27Stat=64;
index_epsPwrSwMs200Stat=65;
index_swStatSolarPanel=66;
index_swStatEwc27=67;
index_swStatPdhs=68;
index_swStatEocHeatZp=69;
index_swStatEocHeatZn=70;
index_swStatAntHeat=71;
index_swStatBpxHeat=72;
index_swStatBusHeat=73;
index_pwrSwCurPdhsHeat=74;
index_pwrSwCurObc=75;
index_pwrSwCurAocs=76;
index_pwrSwCurGps=77;
index_pwrSwCurSBand=78;
index_pwrSwCurAnt=79;
index_pwrSwCurEwc27=80;
index_pwrSwCurMs200=81;
index_pwrSwCurSp=82;
index_pwrSwVolPdhsHeat=83;
index_pwrSwVolObc=84;
index_pwrSwVolAocs=85;
index_pwrSwVolGps=86;
index_pwrSwVolSBand=87;
index_pwrSwVolAnt=88;
index_pwrSwVolEwc27=89;
index_pwrSwVolMs200=90;
index_pwrSwVolSp=91;
index_pwrSwLatCntPdhsHeat=92;
index_pwrSwLatCntObc=93;
index_pwrSwLatCntAocs=94;
index_pwrSwLatCntGps=95;
index_pwrSwLatCntSBand=96;
index_pwrSwLatCntAnt=97;
index_pwrSwLatCntEwc27=98;
index_pwrSwLatCntMs200=99;
index_pwrSwLatCntSp=100;
index_dockLatCntVccAcu=101;
index_dockLatCntVccPdu=102;
index_dockLatCntVbatAcu=103;
index_dockLatCntVbatPdu=104;
index_acuCurDepXp=105;
index_acuCurDepXn=106;
index_acuCurBodyXpXn=107;
index_acuCurBodyYn=108;
index_acuCurBodyYp=109;
index_acuCurDepYn=110;
index_acuVolDepXp=111;
index_acuVolDepXn=112;
index_acuVolBodyXpXn=113;
index_acuVolBodyYn=114;
index_acuVolBodyYp=115;
index_acuVolDepYn=116;
index_dockTemp1=117;
index_dockTemp2=118;
index_pduTemp=119;
index_acuTemp1=120;
index_acuTemp2=121;
index_acuTemp3=122;
index_battery1Temp1=123;
index_battery1Temp2=124;
index_battery1Temp3=125;
index_battery1Temp4=126;
index_battery2Temp1=127;
index_battery2Temp2=128;
index_battery2Temp3=129;
index_battery2Temp4=130;
index_batteryVol=131;
index_chargeCur=132;
index_dischargeCur=133;
index_dockBootcause=134;
index_acuBootcause=135;
index_pduBootcause=136;
index_bpx1Bootcause=137;
index_bpx2Bootcause=138;
index_sBandBootCause=139;
index_sBandBoardTemp=140;
index_sBandPaTemp=141;
index_sBandTxCnt=142;
index_sBandRxCnt=143;
index_sBandBootCnt=144;

hk1_header = [
'hkTimeUTC', 
'timeUtc', 
'selSBband', 
'sBandPStat', 
'sBandRStat', 
'fswOpMode', 
'fswSubOpMode', 
'fswRebootCnt', 
'fswMassMem', 
'obcTemp', 
'edacCnt', 
'spDepStatXp', 
'spDepStatXn', 
'spDepStatYn', 
'spDepGpioStatXp', 
'spDepGpioStatXn', 
'spCepGpioStatYn', 
'antDepStatXp', 
'antDepStatXn', 
'spStationTempXp', 
'spStationTempXn', 
'spStationTempYn', 
'spStationTempYp', 
'spUpTopTempXp', 
'spUpTopTempXn', 
'spUpTopTempYn', 
'spUpBotTempXp', 
'spUpBotTempXn', 
'spUpBotTempYn', 
'adcEocYpZn', 
'adcEocYpZp', 
'adcEocYnZn', 
'adcEocYnZp', 
'adcAntXp', 
'adcAntXn', 
'adcPdhsCaseTemp', 
'adcEwc27CaseTemp', 
'epsDockDevFramStat', 
'epsDockDevAdc1Stat', 
'epsDockDevAdc2Stat', 
'epsDockDevAdc3Stat', 
'epsDockDevTempSenStat', 
'epsDockDevRtcStat', 
'epsMpptMode', 
'epsAcuDevFramStat', 
'epsAcuDevAdc1Stat', 
'epsAcuDevAdc2Stat', 
'epsAcuDevDac1Stat', 
'epsAcuDevDac2Stat', 
'epsAcuDevDac3Stat', 
'epsAcuDevTempSenStat', 
'bat1HeatEnableStat', 
'bat2HeatEnableStat', 
'epsPduDevFramStat', 
'epsPduDevAdc1Stat', 
'epsPduDevAdc2Stat', 
'epsPduDevTempSenStat', 
'epsPwrSwBatStat', 
'epsPwrSwObcStat', 
'epsPwrSwAocsStat', 
'epsPwrSwGpsStat', 
'epsPwrSwSBandStat', 
'epsPwrSwAntStat', 
'epsPwrSwEwc27Stat', 
'epsPwrSwMs200Stat', 
'swStatSolarPanel', 
'swStatEwc27', 
'swStatPdhs', 
'swStatEocHeatZp', 
'swStatEocHeatZn', 
'swStatAntHeat', 
'swStatBpxHeat', 
'swStatBusHeat', 
'pwrSwCurPdhsHeat', 
'pwrSwCurObc', 
'pwrSwCurAocs', 
'pwrSwCurGps', 
'pwrSwCurSBand', 
'pwrSwCurAnt', 
'pwrSwCurEwc27', 
'pwrSwCurMs200', 
'pwrSwCurSp', 
'pwrSwVolPdhsHeat', 
'pwrSwVolObc', 
'pwrSwVolAocs', 
'pwrSwVolGps', 
'pwrSwVolSBand', 
'pwrSwVolAnt', 
'pwrSwVolEwc27', 
'pwrSwVolMs200', 
'pwrSwVolSp', 
'pwrSwLatCntPdhsHeat', 
'pwrSwLatCntObc', 
'pwrSwLatCntAocs', 
'pwrSwLatCntGps', 
'pwrSwLatCntSBand', 
'pwrSwLatCntAnt', 
'pwrSwLatCntEwc27', 
'pwrSwLatCntMs200', 
'pwrSwLatCntSp', 
'dockLatCntVccAcu', 
'dockLatCntVccPdu', 
'dockLatCntVbatAcu', 
'dockLatCntVbatPdu', 
'acuCurDepXp', 
'acuCurDepXn', 
'acuCurBodyXpXn', 
'acuCurBodyYn', 
'acuCurBodyYp', 
'acuCurDepYn', 
'acuVolDepXp', 
'acuVolDepXn', 
'acuVolBodyXpXn', 
'acuVolBodyYn', 
'acuVolBodyYp', 
'acuVolDepYn', 
'dockTemp1', 
'dockTemp2', 
'pduTemp', 
'acuTemp1', 
'acuTemp2', 
'acuTemp3', 
'battery1Temp1', 
'battery1Temp2', 
'battery1Temp3', 
'battery1Temp4', 
'battery2Temp1', 
'battery2Temp2', 
'battery2Temp3', 
'battery2Temp4', 
'batteryVol', 
'chargeCur', 
'dischargeCur', 
'dockBootcause', 
'acuBootcause', 
'pduBootcause', 
'bpx1Bootcause', 
'bpx2Bootcause', 
'sBandBootCause', 
'sBandBoardTemp', 
'sBandPaTemp', 
'sBandTxCnt', 
'sBandRxCnt', 
'sBandBootCnt'
];