index_no=1;
index_timeUtc=2;
index_l0StatWord11=3;
index_l0StatWord12=4;
index_l0StatWord13=5;
index_l0StatWord14=6;
index_wdgSecondCnt=7;
index_momHealth1=8;
index_momHealth2=9;
index_momHealth3=10;
index_momHealth4=11;
index_momHealth5=12;
index_magSrcUsed=13;
index_timeValid=14;
index_refsValid=15;
index_attCtrlHealth1=16;
index_attCtrlHealth2=17;
index_attCtrlHealth3=18;
index_sttOpMode=19;
index_tqRodeFirPack1=20;
index_tqRodeFirPack2=21;
index_tqRodeFirPack3=22;
index_tqRodeFirPack4=23;
index_tqRodeFirPack5=24;
index_tqRodeFirPack6=25;
index_magHealth1=26;
index_magHealth2=27;
index_gpsHealth1=28;
index_gpsHealth2=29;
index_gpsHealth3=30;
index_gpsHealth4=31;
index_gpsHealth5=32;
index_gpsHealth6=33;
index_cssHealth1=34;
index_cssHealth2=35;
index_attDetHealth1=36;
index_attDetHealth2=37;
index_attDetHealth3=38;
index_attCmdHealth1=39;
index_attCmdHealth2=40;
index_attCmdHealth3=41;
index_imuHealth1=42;
index_imuHealth2=43;
index_runLowRateTask=44;
index_attStat=45;
index_tableUploadStat=46;
index_sunPointState=47;
index_taiSeconds=48;
index_posWrtEci1=49;
index_posWrtEci2=50;
index_posWrtEci3=51;
index_velWrtEci1=52;
index_velWrtEci2=53;
index_velWrtEci3=54;
index_qbodyWrtEci1=55;
index_qbodyWrtEci2=56;
index_qbodyWrtEci3=57;
index_qbodyWrtEci4=58;
index_filtSpeedRpm1=59;
index_filtSpeedRpm2=60;
index_filtSpeedRpm3=61;
index_torqDutyCycle1=62;
index_torqDutyCycle2=63;
index_torqDutyCycle3=64;
index_totalMomMag=65;

hk2_header = [
'no',
'timeUtc',
'l0StatWord11',
'l0StatWord12',
'l0StatWord13',
'l0StatWord14',
'wdgSecondCnt',
'momHealth1',
'momHealth2',
'momHealth3',
'momHealth4',
'momHealth5',
'magSrcUsed',
'timeValid',
'refsValid',
'attCtrlHealth1',
'attCtrlHealth2',
'attCtrlHealth3',
'sttOpMode',
'tqRodeFirPack1',
'tqRodeFirPack2',
'tqRodeFirPack3',
'tqRodeFirPack4',
'tqRodeFirPack5',
'tqRodeFirPack6',
'magHealth1',
'magHealth2',
'gpsHealth1',
'gpsHealth2',
'gpsHealth3',
'gpsHealth4',
'gpsHealth5',
'gpsHealth6',
'cssHealth1',
'cssHealth2',
'attDetHealth1',
'attDetHealth2',
'attDetHealth3',
'attCmdHealth1',
'attCmdHealth2',
'attCmdHealth3',
'imuHealth1',
'imuHealth2',
'runLowRateTask',
'attStat',
'tableUploadStat',
'sunPointState',
'taiSeconds',
'posWrtEci1',
'posWrtEci2',
'posWrtEci3',
'velWrtEci1',
'velWrtEci2',
'velWrtEci3',
'qbodyWrtEci1',
'qbodyWrtEci2',
'qbodyWrtEci3',
'qbodyWrtEci4',
'filtSpeedRpm1',
'filtSpeedRpm2',
'filtSpeedRpm3',
'torqDutyCycle1',
'torqDutyCycle2',
'torqDutyCycle3',
'totalMomMag',
]