ROW_LIMIT = 5000
SECRET_KEY = 'Po4kCDDZnHK9cfhytBrke8Bti99L8A9Rj7BPRhV/fnHwM/iQJUkctrhL'
SQLALCHEMY_DATABASE_URI = 'sqlite:////sqlite_db/superset.db'
WTF_CSRF_ENABLED = True
WTF_CSRF_EXEMPT_LIST = []
WTF_CSRF_TIME_LIMIT = 60 * 60 * 24 * 365
MAPBOX_API_KEY = ''
